### ISSUE TITLE
Players resumes even after user pausing

### ISSUE THREAD

**Issue by jonyroda97** [Tester798/ffzenhancing#12] opened 2020-11-21 00:02 UTC
Even if it's the user pausing the player it auto resumes (with the `Auto Reload on Video Freeze` option)
Maybe there's a way to check if it's the user pausing the player and not resuming?

**Comment by Tester798** [comment] 2020-11-21 01:04
I'm not able to reproduce the issue.
What web browser you are using? What value is set in `Auto Reload on Video Freeze After` option? Do you see the playback resumes right after you press pause in the player and wait for some time or you are switching to different tab in your browser or different window in your system?

**Comment by jonyroda97** [comment] 2020-11-21 20:37
> What web browser you are using?

Chrome

> What value is set in `Auto Reload on Video Freeze After` option?

4 (Default)

> Do you see the playback resumes right after you press pause in the player and wait for some time or you are switching to different tab in your browser or different window in your system?

Sometimes it takes the time set on the option, sometimes less but normally takes the time set.
I tried changing the value and it took the time set on the option to resume.
On testing now, I stayed on the tab and window until it occurred but I detected this problem while pausing and changing tabs and/or window.

**Comment by Tester798** [comment] 2020-11-21 22:06
I think I was able to reproduce it once when was changing windows (or tabs, can't remember now). After that I tried to reproduce the issue again but wasn't able to. I think this can be related to tab freezing/unloading in Chrome or maybe to Twitch's own tab inactive handler (video quality change). Or maybe it's something else.
It's kinda tricky to detect when user paused the video because sometimes video lags on twitch are looking as paused video too.
Maybe we can detect actual press on "play/pause" button to determine player pause state instead of getting it from element itself. Will need to experiment with it.

**Comment by Tester798** [comment] 2020-11-21 23:01
Ok, maybe resume was caused by automatic player reset on errors like "#4000" even if player was on pause. Added a check now in 6.35 before player reset. But not sure if it will make player auto reset stop on some errors now.
Please let me know if you still see that the player auto resumes after it was paused or if auto reset on errors like "#4000" stopped working.

**Comment by Tester798** [comment] 2020-11-23 09:22
Hmm, looks like fix in 6.35 was preventing player reset on errors like "#4000" so I tried to use a different way of detecting when the player is paused in 6.36.
Also I noticed that twitch itself can resume the playback (for example if pause was done right after network error happened). So now I'm not even sure if resume was caused by this extension.
That's why I'm going to close the issue right now, but feel free to comment here is you will be able to reproduce the issue and would want to provide reproducing steps.

**Closed as completed by Tester798** 2020-11-23 09:22 UTC
